### ISSUE TITLE
Missing `scheduler_hints` causes a panic

### ISSUE THREAD

**Issue by sersorrel** [sardinasystems/fleeting-plugin-openstack#20]
https://github.com/sardinasystems/fleeting-plugin-openstack/commit/6eeff7c17c9f3c171b2bb972dacbba3f8cd83994 introduced a bug: if the config file doesn't contain `scheduler_hints`, fleeting-plugin-openstack will crash:

```
panic: value method github.com/gophercloud/gophercloud/v2/openstack/compute/v2/servers.SchedulerHintOpts.ToSchedulerHintsMap called using nil *SchedulerHintOpts pointer

goroutine 44 [running]:
github.com/gophercloud/gophercloud/v2/openstack/compute/v2/servers.(*SchedulerHintOpts).ToSchedulerHintsMap(0xc000298fe8?)
        <autogenerated>:1 +0xa6
github.com/gophercloud/gophercloud/v2/openstack/compute/v2/servers.Create({0xd5b9a0, 0xc0002950e0}, 0xc000193d60, {0xd54da0, 0xc0001f51e0}, {0xd54dc0, 0x0})
        /root/go/pkg/mod/github.com/gophercloud/gophercloud/v2@v2.0.0-rc.1/openstack/compute/v2/servers/requests.go:593 +0xf7
github.com/sardinasystems/fleeting-plugin-openstack.(*InstanceGroup).createInstance(0xc000172dc8, {0xd5b9a0, 0xc0002950e0})
        /root/go/pkg/mod/github.com/sardinasystems/fleeting-plugin-openstack@v0.0.0-20240528073735-c132754c1410/provider.go:224 +0x209
github.com/sardinasystems/fleeting-plugin-openstack.(*InstanceGroup).Increase(0xc000172dc8, {0xd5b9a0, 0xc0002950e0}, 0x2)
        /root/go/pkg/mod/github.com/sardinasystems/fleeting-plugin-openstack@v0.0.0-20240528073735-c132754c1410/provider.go:148 +0x9a
gitlab.com/gitlab-org/fleeting/fleeting/internal/plugin.(*instanceGroupGRPCServer).Increase(0x12533d0?, {0xd5b9a0?, 0xc0002950e0?}, 0x4aace5?)
        /root/go/pkg/mod/gitlab.com/gitlab-org/fleeting/fleeting@v0.0.0-20240515132427-669ba1469989/internal/plugin/instance_group_server.go:64 +0x29
gitlab.com/gitlab-org/fleeting/fleeting/internal/plugin/proto._InstanceGroup_Increase_Handler({0xb18920, 0xc00018a840}, {0xd5b9a0, 0xc0002950e0}, 0xc0001e9180, 0x0)
        /root/go/pkg/mod/gitlab.com/gitlab-org/fleeting/fleeting@v0.0.0-20240515132427-669ba1469989/internal/plugin/proto/instance_group_grpc.pb.go:220 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000110e00, {0xd5b9a0, 0xc000295050}, {0xd60b40, 0xc000130180}, 0xc0002a0240, 0xc00018a8d0, 0x1260658, 0x0)
        /root/go/pkg/mod/google.golang.org/grpc@v1.64.0/server.go:1379 +0xdf8
google.golang.org/grpc.(*Server).handleStream(0xc000110e00, {0xd60b40, 0xc000130180}, 0xc0002a0240)
        /root/go/pkg/mod/google.golang.org/grpc@v1.64.0/server.go:1790 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        /root/go/pkg/mod/google.golang.org/grpc@v1.64.0/server.go:1029 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 16
        /root/go/pkg/mod/google.golang.org/grpc@v1.64.0/server.go:1040 +0x125
```

(You can work around this by setting `scheduler_hints = {}` in the runner config.)

The relevant call is this one to `servers.Create`, with a null `spec.SchedulerHints`:

https://github.com/sardinasystems/fleeting-plugin-openstack/blob/0b2a26fd5cf30d963258cddecc97d9d718b81221/provider.go#L224

**Comment by vooon** [comment]
Ah, yes, already encountered this problem on other project. Should be fixed now.
